### PR TITLE
Load libEGL.so.1 or libEGL.so inside load_required

### PR DESCRIPTION
**Pull request by Gordon-F**
Changes introduced in https://github.com/timothee-haudebourg/khronos-egl/commit/fa02f969e64898065b807d2200d769d0128375f4 break `Android` support.

### CODE REVIEW

**Comment by timothee-haudebourg** [comment]
Looks good, thanks.

**Comment by Gordon-F** [comment]
@timothee-haudebourg Could you release a new version?

**Comment by timothee-haudebourg** [comment]
I planned to do that later today.

**Comment by Gordon-F** [comment]
@timothee-haudebourg Thank you!

**Comment by timothee-haudebourg** [comment]
@Gordon-F It's done, version 4.1.0 includes your changes. Thanks again.

**Pull request merged**
